# 路径: configs/train_dppo.yaml

# 🌟 核心：告诉 Hydra 去哪里拉取基础配置
defaults:
  - _self_                      # 允许本文件覆盖上面的默认值
  - policy: ft_zed_diffusion   

resume: false
resume_path: none
device: "cuda:0"  # cuda或cpu

hydra:
  run:
    dir: outputs/finetune/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.task}_${hydra.runtime.choices.policy}
    # dir: src/av-aloha/DPPO/outputs/pretrain/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: ${env.task}_${hydra.runtime.choices.policy}_${now:%Y-%m-%d}_${now:%H-%M-%S}

training:
  pretrained_ckpt_path: "outputs/pretrain/train/.../checkpoints/050000"
  rollout_steps: 500


wandb:
  enable: true
  # Set to true to disable saving an artifact despite save_checkpoint == True
  disable_artifact: true # 不保存artifact，即不上传权重模型
  project: ${env.task}_finetune  #项目名称
  notes: ""
  save_code: false  # 是否保存代码

seed: ???